pipeline {
    agent any
    stages {
        stage ('GIT Checkout'){
            steps {
                git changelog: false, poll: false, url: 'https://github.com/ayushk1804/cyware-assignment.git'
            }
        }
        
        stage('build') {
            steps {
                sh 'pip install -r Part 1/webapp/requirements.txt'
            }
        }
        
        stage ('Test'){
            steps {
                sh 'pytest Part 1/webapp/test_app.py'
            }
        }
    }
}